### ISSUE TITLE
Unable to unforge game.dcb

### ISSUE THREAD

**Issue by necrogami** [dolkensp/unp4k#20]
```
Warning Tag.eb6425f0-f7a0-4a1d-a4b1-a2ed73d5ce56 doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning Tag.5f4faa96-65fb-4771-a59f-3c316b866302 doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning Tag.336ec2d5-eda4-42da-b001-927d4685c4b9 doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning Tag.13a35f23-6ef5-4de3-888b-32f8995c6910 doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning Tag.614a7309-3041-4ead-b00c-19b0f6e51d11 doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning Tag.cfd28b7d-b3a7-49c4-834f-42a2714b0f8d doesn't match libs/foundry/records/tagdatabase/tagdatabase.tagdatabase.xml
Warning UnitTestSubRecord.UnitTestSubRecordA doesn't match libs/foundry/records/unittest.unittestb.xml
Warning UnitTestSubRecord.UnitTestSubRecordB doesn't match libs/foundry/records/unittest.unittestb.xml
Warning ScreenEffects_Effect.2bd09f5c-4645-43ba-9b3b-db1b0a47009f doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.4761f510-f7bc-4af9-8eb2-92b012a976c0 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.e42cea73-2429-407e-9622-5682d8a44d8a doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.a56fc94d-91f9-4adc-803d-2f63e345e252 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.9138f15c-6e77-450c-8976-151b8e542297 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.e38b3a54-491d-45a9-8140-8eab35d87488 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.523ecff4-29ea-4ea7-94f5-2cb307f22b6a doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.9736fbf9-eb33-497c-b95a-1392803a5058 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning VoiceSingle.VoiceSingle7 doesn't match libs/foundry/records/voicebundle/bhuntpilot01.xml
Warning VoiceSingle.CruPatrol1 doesn't match libs/foundry/records/voicebundle/crupatrol.xml
```

When i try to run unforge.exe Game.dcb i get these errors, how can i run unforge on the game.dcb no files are generated from this.

**Comment by peter-dolkens** [comment]
Hi @necrogami - these warnings are expected.

These are simply warning that the filename in the game.dcb doesn't match the XML tag - if you work directly from the converted `game.xml`, it's not an issue.

If you try and work from the explicitly extracted files however, for some entries, there's multiple tags with the same filename. This means that multiple they will overwrite earlier entries.

e.g.

```
Warning ScreenEffects_Effect.9138f15c-6e77-450c-8976-151b8e542297 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
Warning ScreenEffects_Effect.e38b3a54-491d-45a9-8140-8eab35d87488 doesn't match libs/foundry/records/vfx/generalscreeneffects.xml
```

These both try and export to `libs/foundry/records/vfx/generalscreeneffects.xml` which results in them overwriting each other.

`game.xml` doesn't suffer this problem, because ALL content is included in a single file.

> no files are generated from this

can you tell me how you're trying to run/process the tools?

* Are you just running the command `unforge game.dcb`?
* Are you using any explicit pathing e.g. `unforge s:\StarCitizen\game.dcb`?
* Is `unforge.exe` in the same directory as `game.dcb`?

I've confirmed things are working on my machine at least, you can see the `Game.xml` file and the `libs` folder with all the records in it in my screenshot below.

![image](https://user-images.githubusercontent.com/469666/75504957-d8e2ca80-59d1-11ea-88d7-4b5066dc5a4b.png)

**Comment by necrogami** [comment]
So i redid it the way you did it, it worked this time. Doing a full dump and then doing the unforge game.dcb resulted in a blank libs/foundry folders. All the folders existed but no files.

Doing it then way the image shows resulted in properly extracted files. Thanks!

**Comment by 1ch00** [comment]
Hi,

since PTU 3.13 is out I wanted to extract the data as well and I did it as you showed in the screenshot. 

But it then says:
![03-04-_2021_23-22-36](https://user-images.githubusercontent.com/63108997/113491786-87114b80-94d3-11eb-9c64-526461f2e225.png)
